"""Public API for aiofarmad."""

import importlib.metadata

from .client import FarmadClient, TokenRefreshCallback
from .exceptions import (
    FarmadAuthenticationError,
    FarmadAuthorizationError,
    FarmadClientClosedError,
    FarmadCommunicationError,
    FarmadEhealthAuthorizationRequiredError,
    FarmadError,
    FarmadInvalidResponseError,
    FarmadMfaRequiredError,
    FarmadMissingIdentifierError,
    FarmadNotFoundError,
    FarmadTimeoutError,
)
from .models import (
    AccountMembership,
    BasketItem,
    BasketLine,
    BasketPayment,
    CatalogProduct,
    CatalogProductCode,
    CatalogProductPrice,
    CatalogProductStock,
    ConversationSummary,
    CustomerBasket,
    DraftBasket,
    DraftProduct,
    FarmadAccount,
    FarmadMessage,
    FarmadPatient,
    FarmadTokens,
    KavaProduct,
    MedicationDayScheme,
    MedicationIntakeMoment,
    MedicationNondailyProduct,
    MedicationSchemeProduct,
    MedicationSchemeProductEntry,
    MedicationTemporality,
    MessageDraft,
    MessageDraftAttachment,
    MessageDraftAttachmentVariant,
    PatientInPharmacy,
    Pharmacy,
    PharmacyPreferences,
    Prescription,
    ServiceMessage,
)

try:
    __version__ = importlib.metadata.version("aiofarmad")
except importlib.metadata.PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "AccountMembership",
    "BasketItem",
    "BasketLine",
    "BasketPayment",
    "CatalogProduct",
    "CatalogProductCode",
    "CatalogProductPrice",
    "CatalogProductStock",
    "ConversationSummary",
    "CustomerBasket",
    "DraftBasket",
    "DraftProduct",
    "FarmadAccount",
    "FarmadAuthenticationError",
    "FarmadAuthorizationError",
    "FarmadClient",
    "FarmadClientClosedError",
    "FarmadCommunicationError",
    "FarmadEhealthAuthorizationRequiredError",
    "FarmadError",
    "FarmadInvalidResponseError",
    "FarmadMessage",
    "FarmadMfaRequiredError",
    "FarmadMissingIdentifierError",
    "FarmadNotFoundError",
    "FarmadPatient",
    "FarmadTimeoutError",
    "FarmadTokens",
    "KavaProduct",
    "MedicationDayScheme",
    "MedicationIntakeMoment",
    "MedicationNondailyProduct",
    "MedicationSchemeProduct",
    "MedicationSchemeProductEntry",
    "MedicationTemporality",
    "MessageDraft",
    "MessageDraftAttachment",
    "MessageDraftAttachmentVariant",
    "PatientInPharmacy",
    "Pharmacy",
    "PharmacyPreferences",
    "Prescription",
    "ServiceMessage",
    "TokenRefreshCallback",
    "__version__",
]
